"use client";

import { FormEvent, useEffect, useState } from "react";
import { KeyRound, LockKeyhole, Medal, UserRound, X } from "lucide-react";
import { createUserWithEmailAndPassword, deleteUser, GoogleAuthProvider, onAuthStateChanged, sendPasswordResetEmail, signInWithEmailAndPassword, signInWithPopup, signOut, updateProfile } from "firebase/auth";
import { doc, getDoc, onSnapshot, setDoc } from "firebase/firestore";
import { getDownloadURL, ref, uploadBytes } from "firebase/storage";
import { firebaseAuth, firebaseDb, firebaseStorage } from "./firebase";

type User = { email: string; name: string; password: string; points: number; photo?: string };
const defaultRank: { name: string; points: number }[] = [];
const accountsKey = "ocean-guide-accounts";
const readAccounts = (): User[] => { try { const raw = localStorage.getItem(accountsKey); return raw ? JSON.parse(raw) : []; } catch { return []; } };
const compactPhoto = (dataUrl: string) => new Promise<string>((resolve) => { const image = new Image(); image.onload = () => { const canvas = document.createElement("canvas"); canvas.width = 192; canvas.height = 192; const context = canvas.getContext("2d"); if (!context) return resolve(dataUrl); const scale = Math.max(192 / image.width, 192 / image.height); const width = image.width * scale; const height = image.height * scale; context.drawImage(image, (192 - width) / 2, (192 - height) / 2, width, height); resolve(canvas.toDataURL("image/jpeg", 0.65)); }; image.src = dataUrl; });

export default function AccountWidget() {
  const [open, setOpen] = useState<"login" | "signup" | "reset" | "rank" | null>(null);
  const [user, setUser] = useState<User | null>(null);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => onAuthStateChanged(firebaseAuth, (fbUser) => { if (!fbUser) { setUser(null); localStorage.removeItem("ocean-guide-user"); return; } let saved: Partial<User> = {}; try { saved = JSON.parse(localStorage.getItem("ocean-guide-user") || "{}"); } catch { saved = {}; } const emailKey = (fbUser.email || "").toLowerCase(); const savedPhoto = localStorage.getItem(`ocean-guide-photo-${emailKey}`) || ""; const next = { email: fbUser.email || "", name: fbUser.displayName || fbUser.email?.split("@")[0] || "사용자", password: "", points: saved.points || 0, photo: fbUser.photoURL || savedPhoto || (saved as User & { photo?: string }).photo || "" }; setUser(next); localStorage.setItem("ocean-guide-user", JSON.stringify(next)); }), []);
  useEffect(() => { const unsubscribe = onAuthStateChanged(firebaseAuth, async (fbUser) => { if (!fbUser) return; try { const ref = doc(firebaseDb, "users", fbUser.uid); const snap = await getDoc(ref); const remote = snap.exists() ? snap.data() as Partial<User> : {}; const current = JSON.parse(localStorage.getItem("ocean-guide-user") || "{}"); const merged = { email: fbUser.email || current.email || "", name: remote.name || fbUser.displayName || current.name || fbUser.email?.split("@")[0] || "사용자", password: "", points: Number(remote.points ?? current.points ?? 0), photo: remote.photo || fbUser.photoURL || current.photo || "" }; await setDoc(ref, merged, { merge: true }); localStorage.setItem("ocean-guide-user", JSON.stringify(merged)); setUser(merged); window.dispatchEvent(new Event("ocean-auth-changed")); } catch { /* Firestore rules/setup may be pending; local auth remains usable. */ } }); return () => unsubscribe(); }, []);
  useEffect(() => { let stop: (() => void) | undefined; const authStop = onAuthStateChanged(firebaseAuth, (fbUser) => { stop?.(); if (!fbUser) return; stop = onSnapshot(doc(firebaseDb, "users", fbUser.uid), (snap) => { if (!snap.exists()) return; const remote = snap.data() as Partial<User>; const current = JSON.parse(localStorage.getItem("ocean-guide-user") || "{}"); const next = { ...current, email: fbUser.email || current.email || "", name: remote.name || current.name || fbUser.displayName || "사용자", points: Number(remote.points ?? current.points ?? 0), photo: remote.photo || fbUser.photoURL || current.photo || "" }; localStorage.setItem("ocean-guide-user", JSON.stringify(next)); setUser(next); window.dispatchEvent(new Event("ocean-auth-changed")); }); }); return () => { authStop(); stop?.(); }; }, []);
  useEffect(() => { const savePhoto = async () => { const current = firebaseAuth.currentUser; if (!current) return; const cached = JSON.parse(localStorage.getItem("ocean-guide-user") || "{}"); const photo = cached.photo || current.photoURL; if (!photo) return; try { await setDoc(doc(firebaseDb, "users", current.uid), { photo, email: current.email || "" }, { merge: true }); } catch { /* Auth photoURL remains the fallback. */ } }; window.addEventListener("ocean-auth-changed", savePhoto); return () => window.removeEventListener("ocean-auth-changed", savePhoto); }, []);
  useEffect(() => { const savePhotoToAccount = async () => { const current = firebaseAuth.currentUser; if (!current) return; const cached = JSON.parse(localStorage.getItem("ocean-guide-user") || "{}"); if (!cached.photo?.startsWith("data:image/")) return; try { const photo = await compactPhoto(cached.photo); await setDoc(doc(firebaseDb, "users", current.uid), { photo, email: current.email || "" }, { merge: true }); const next = { ...cached, photo }; localStorage.setItem("ocean-guide-user", JSON.stringify(next)); setUser(next); } catch { setMessage("프로필 사진 원격 저장에 실패했습니다. Firebase Firestore의 인증 사용자 쓰기 권한을 확인해주세요."); } }; window.addEventListener("ocean-auth-changed", savePhotoToAccount); return () => window.removeEventListener("ocean-auth-changed", savePhotoToAccount); }, []);
  useEffect(() => { if (open === "login") setEmail(localStorage.getItem("ocean-guide-last-email") || ""); }, [open]);
  useEffect(() => { const openLogin = () => setOpen("login"); window.addEventListener("ocean-open-login", openLogin); return () => window.removeEventListener("ocean-open-login", openLogin); }, []);
  useEffect(() => {
    const bar = document.querySelector(".account-fab"); if (!bar) return;
    bar.querySelectorAll(".auth-action, .previous-login-btn").forEach((el) => el.remove());
    if (!user) { const last = localStorage.getItem("ocean-guide-last-email"); if (last) { const previous = document.createElement("button"); previous.className = "previous-login-btn"; previous.textContent = "이전 계정으로 로그인"; previous.onclick = () => { setEmail(last); setOpen("login"); }; bar.append(previous); } return; }
    const logout = document.createElement("button"); logout.className = "auth-action logout-btn"; logout.textContent = "로그아웃";
    logout.onclick = async () => { if (!window.confirm("정말 로그아웃하시겠습니까?")) return; localStorage.setItem("ocean-guide-last-email", user.email); await signOut(firebaseAuth); setOpen(null); window.dispatchEvent(new Event("ocean-auth-changed")); };
    const withdraw = document.createElement("button"); withdraw.className = "auth-action withdraw-btn"; withdraw.textContent = "탈퇴";
    withdraw.onclick = async () => { if (!window.confirm("계정을 탈퇴하시겠습니까? 계정이 영구 삭제됩니다.")) return; if (firebaseAuth.currentUser) await deleteUser(firebaseAuth.currentUser); localStorage.removeItem("ocean-guide-user"); localStorage.removeItem("ocean-guide-last-email"); setOpen(null); window.dispatchEvent(new Event("ocean-auth-changed")); };
    bar.append(logout, withdraw);
  }, [user]);
  useEffect(() => { const list = document.querySelector<HTMLElement>(".ranking-list"); if (!list) return; document.querySelectorAll<HTMLElement>(".ranking-list > div").forEach((row, index) => { row.style.display = index < 10 ? "" : "none"; }); if (!list.querySelector(".ranking-empty")) { const empty = document.createElement("p"); empty.className = "ranking-empty"; empty.textContent = user ? "현재 내 랭킹만 표시됩니다. 다른 사용자 랭킹은 실제 집계 후 제공됩니다." : "로그인하면 내 랭킹을 확인할 수 있습니다."; list.appendChild(empty); } }, [open, user]);
  useEffect(() => { if (open !== "login") return; const form = document.querySelector(".account-form"); if (!form || form.querySelector(".google-login-btn")) return; const divider = document.createElement("div"); divider.className = "social-divider"; divider.textContent = "또는"; const google = document.createElement("button"); google.type = "button"; google.className = "google-login-btn"; google.textContent = "Google 계정으로 로그인"; google.onclick = async () => { try { await signInWithPopup(firebaseAuth, new GoogleAuthProvider()); setOpen(null); } catch { setMessage("Google 로그인에 실패했습니다. 다시 시도해주세요."); } }; form.append(divider, google); }, [open]);
  useEffect(() => { const bar = document.querySelector<HTMLElement>(".account-fab"); if (!bar || bar.querySelector(".theme-toggle")) return; const button = document.createElement("button"); button.className = "theme-toggle"; const apply = (dark: boolean) => { document.documentElement.classList.toggle("dark-mode", dark); button.textContent = dark ? "☀️ 라이트 모드" : "🌙 다크 모드"; localStorage.setItem("ocean-guide-theme", dark ? "dark" : "light"); }; const saved = localStorage.getItem("ocean-guide-theme") === "dark"; apply(saved); button.onclick = () => apply(!document.documentElement.classList.contains("dark-mode")); bar.appendChild(button); }, [user]);
  useEffect(() => { const move = () => { const sidebar = document.querySelector<HTMLElement>(".site-sidebar"); const bar = document.querySelector<HTMLElement>(".account-fab"); if (!sidebar || !bar) return; const existing = sidebar.querySelector(".account-side-actions"); const slot = existing || document.createElement("div"); slot.className = "account-side-actions"; if (!existing) { const label = document.createElement("span"); label.textContent = "계정"; slot.appendChild(label); sidebar.appendChild(slot); } Array.from(bar.querySelectorAll<HTMLElement>(".auth-action, .previous-login-btn")).forEach((button) => slot.appendChild(button)); const rank = Array.from(bar.children).find((child) => child instanceof HTMLElement && child.textContent?.includes("랭킹")); if (rank) slot.appendChild(rank); }; move(); const timer = window.setInterval(move, 250); return () => window.clearInterval(timer); }, [user]);
  const close = () => { setOpen(null); setMessage(""); setEmail(""); setPassword(""); setName(""); };
  const submit = async (e: FormEvent) => { e.preventDefault();
    try {
      if (open === "reset") { await sendPasswordResetEmail(firebaseAuth, email.trim()); setMessage(`${email} 주소로 재설정 이메일을 보냈습니다.`); return; }
      if (open === "signup") { const credential = await createUserWithEmailAndPassword(firebaseAuth, email.trim(), password); if (name.trim()) await updateProfile(credential.user, { displayName: name.trim() }); localStorage.setItem("ocean-guide-last-email", email.trim()); setMessage("가입이 완료되었습니다."); return; }
      const credential = await signInWithEmailAndPassword(firebaseAuth, email.trim(), password); localStorage.setItem("ocean-guide-last-email", credential.user.email || email.trim()); setMessage("로그인되었습니다.");
    } catch (error) { const code = error instanceof Error ? error.message : "인증에 실패했습니다."; setMessage(code.includes("auth/email-already-in-use") ? "이미 가입된 이메일입니다." : code.includes("auth/invalid-credential") ? "이메일 또는 비밀번호를 확인해주세요." : "인증에 실패했습니다. 입력 내용을 확인해주세요."); }
  };
  return <><div className="account-fab"><button onClick={() => setOpen(user ? "rank" : "login")}><UserRound size={16} /> {user ? user.name : "로그인"}</button><button onClick={() => setOpen("rank")}><Medal size={16} /> 랭킹</button></div>{open && <div className="modal-backdrop" onMouseDown={close}><div className="modal account-modal" onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><h3>{open === "rank" ? "마일리지 랭킹" : open === "signup" ? "회원가입" : open === "reset" ? "비밀번호 찾기" : "로그인"}</h3><button onClick={close}><X size={20} /></button></div>{open === "rank" ? <div className="ranking-list">{(user ? [{ name: user.name, points: user.points }, ...defaultRank] : defaultRank).sort((a, b) => b.points - a.points).map((r, i) => <div key={`${r.name}-${i}`}><b>{i + 1}</b><span><strong>{r.name}</strong><small>부산 바다 활동가</small></span><em>{r.points.toLocaleString()}P</em></div>)}</div> : <form className="account-form" onSubmit={submit}><label>이메일<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" required /></label>{open === "signup" && <label>이름<input value={name} onChange={(e) => setName(e.target.value)} placeholder="이름" /></label>}{open !== "reset" && <label>비밀번호<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="8자 이상" required /></label>}<button className="submit-btn" type="submit">{open === "signup" ? "가입하기" : open === "reset" ? <><KeyRound size={16} /> 재설정 이메일 보내기</> : <><LockKeyhole size={16} /> 로그인</>}</button>{message && <p className="account-message">{message}</p>}<div className="account-links">{open === "login" && <><button type="button" onClick={() => setOpen("signup")}>회원가입</button><button type="button" onClick={() => setOpen("reset")}>비밀번호 찾기</button></>}{open !== "login" && <button type="button" onClick={() => setOpen("login")}>로그인으로 돌아가기</button>}</div></form>}</div></div>}</>;
}
