"use client";

import { FormEvent, useEffect, useState } from "react";
import { KeyRound, LockKeyhole, Medal, UserRound, X } from "lucide-react";

type User = { email: string; name: string; password: string; points: number };
const defaultRank = [{ name: "해변지킴이", points: 2480 }, { name: "파도수호자", points: 2210 }, { name: "그린러너", points: 1980 }, { name: "바다친구", points: 1650 }];

export default function AccountWidget() {
  const [open, setOpen] = useState<"login" | "signup" | "reset" | "rank" | null>(null);
  const [user, setUser] = useState<User | null>(null);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { const saved = localStorage.getItem("ocean-guide-user"); if (saved) setUser(JSON.parse(saved)); }, []);
  const close = () => { setOpen(null); setMessage(""); setEmail(""); setPassword(""); setName(""); };
  const submit = (e: FormEvent) => { e.preventDefault(); if (open === "reset") { setMessage(`${email} 주소로 비밀번호 재설정 안내를 보냈습니다. (데모)`); return; } if (open === "signup") { const next = { email, name: name || email.split("@")[0], password, points: 0 }; localStorage.setItem("ocean-guide-user", JSON.stringify(next)); setUser(next); setMessage("가입이 완료되었습니다."); return; } const saved = localStorage.getItem("ocean-guide-user"); const found = saved ? JSON.parse(saved) as User : null; if (found && found.email === email && found.password === password) { setUser(found); setMessage("로그인되었습니다."); } else setMessage("이메일 또는 비밀번호를 확인해주세요."); };
  return <><div className="account-fab"><button onClick={() => setOpen(user ? "rank" : "login")}><UserRound size={16} /> {user ? user.name : "로그인"}</button><button onClick={() => setOpen("rank")}><Medal size={16} /> 랭킹</button></div>{open && <div className="modal-backdrop" onMouseDown={close}><div className="modal account-modal" onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><h3>{open === "rank" ? "마일리지 랭킹" : open === "signup" ? "회원가입" : open === "reset" ? "비밀번호 찾기" : "로그인"}</h3><button onClick={close}><X size={20} /></button></div>{open === "rank" ? <div className="ranking-list">{(user ? [{ name: user.name, points: user.points }, ...defaultRank] : defaultRank).sort((a, b) => b.points - a.points).map((r, i) => <div key={`${r.name}-${i}`}><b>{i + 1}</b><span><strong>{r.name}</strong><small>부산 바다 활동가</small></span><em>{r.points.toLocaleString()}P</em></div>)}</div> : <form className="account-form" onSubmit={submit}><label>이메일<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" required /></label>{open === "signup" && <label>이름<input value={name} onChange={(e) => setName(e.target.value)} placeholder="이름" /></label>}{open !== "reset" && <label>비밀번호<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="8자 이상" required /></label>}<button className="submit-btn" type="submit">{open === "signup" ? "가입하기" : open === "reset" ? <><KeyRound size={16} /> 재설정 이메일 보내기</> : <><LockKeyhole size={16} /> 로그인</>}</button>{message && <p className="account-message">{message}</p>}<div className="account-links">{open === "login" && <><button type="button" onClick={() => setOpen("signup")}>회원가입</button><button type="button" onClick={() => setOpen("reset")}>비밀번호 찾기</button></>}{open !== "login" && <button type="button" onClick={() => setOpen("login")}>로그인으로 돌아가기</button>}</div></form>}</div></div>}</>;
}
